### ISSUE TITLE
Listing movies

### ISSUE THREAD

**Issue by vitorverasm** [vitorverasm/moviedb-app#5]
## Description

List all movies, popular, by categories using the [MovieDB API](https://developers.themoviedb.org/3/getting-started/authentication).

## Task
- [x] Create API project and configure API key
- [x] Setup restful-react provider
- [x] Generate api types from api spec
- [x] Create listings(popular and by params)
